-- Seed data generated from Altahera System DB.xlsx
SET session_replication_role = 'replica';

-- 1. Branches
INSERT INTO branches (id, name) VALUES ('b1', 'روكسي') ON CONFLICT (id) DO NOTHING;
INSERT INTO branches (id, name) VALUES ('b2', 'المقطم') ON CONFLICT (id) DO NOTHING;
INSERT INTO branches (id, name) VALUES ('b3', 'فيصل') ON CONFLICT (id) DO NOTHING;
INSERT INTO branches (id, name) VALUES ('b4', 'حدائق الأهرام') ON CONFLICT (id) DO NOTHING;
INSERT INTO branches (id, name) VALUES ('b5', 'المنيا') ON CONFLICT (id) DO NOTHING;
INSERT INTO branches (id, name) VALUES ('b6', 'السيده زينب') ON CONFLICT (id) DO NOTHING;
INSERT INTO branches (id, name) VALUES ('b7', 'مبت غمر') ON CONFLICT (id) DO NOTHING;

-- 2. Doctors
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1001', 'انس عبد العزيز', 'جميع الفحوص ما عدا الاتى : 1 - الوصله الوريديه 2- دوبلر على الكلى المزروعه و الغير مزروعة 3-فحوصات الثدى 4 - دوبلر على القضيب بدون حقن 5- سونار عضلات ومفاصل 6- دوبلر على المخ اطفال او كبار 7- سحب عينات الثدى 8- سونار بروستاتا من الداخل T.RECTAL U.S', 'b4') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1002', 'محمد الدهشان', 'جميع الفحوص ما عدا الاتى : 1 - الوصله الوريديه 2- دوبلر على الكلى المزروعه والغير مزروعه 3-فحوصات الثدى 4 - دوبلر على القضيب 5- سونار عضلات ومفاصل 6- سونار انسجه رخويه 7- دوبلر على المخ اطفال او كبار 8- سونار بروستاتا من الداخل T.RECTAL U.S', 'b4') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1003', 'سلمى', 'جميع الفحوص ما عدا الاتى : 1- دوبلر على الوصله الوريديه الكلى المروعة وغير المزروعه 2 - دزبلر على الخصية 3 - دوبلر على القضيب 4- سونار عضلات ومفاصل 3D - 4 D/ D.FETAL 5- دوبلر على المخ اطفال او كبار 6 - سحب العينات', 'b4') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1004', 'دعاء جابر', 'جميع الفحوص ما عدا الاتى : 1- دوبلر على الوصله الوريديه 2 - دزبلر على الخصية 3 - دوبلر على القضيب 4- سونار عضلات ومفاصل 3D - 4 D الكلى المزروعة وغير المزروعه 7- سونار انسجه رخويه 8- دوبلر على المخ اطفال او كبار', 'b4') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1005', 'كريم حسين', 'جميع الفحوص ما عدا الاتى : 1- دوبلر على الوصله الوريديه 2 - دزبلر على الكلى المزروعه وغير المزروعه 3 - دوبلر على القضيب 4- سونار عضلات ومفاصل 3D - 4 D 5- سونار انسجه رخويه 6- دوبلر على المخ اطفال او كبار 7- سونار على البروستاتا من خلال الشرج', 'b4') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1006', 'غفران', 'جميع الفحوص ما عدا الاتى : 1 - الوصله الوريديه دوبلر على الكلى المزروعه والغير مزروعه 2- سونار بروستاتا من الداخل T.RECTAL U.S 3-فحوصات الثدى 4 - دوبلر على القضيب 5- سونار عضلات ومفاصل 6- دوبلر على المخ اطفال او كبار', 'b4') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1007', 'د . سارة', 'جميع الفحوص ما عدا الاتى : 1 - الوصله الوريديه 2- دوبلر على الكلى المزروعه دوبلر على القضيب دوبلر على الشرايين للاطراف سونار عضلات ومفاصل سونار على البروستاتا من خلال الشرج سحب العينات دوبلر على المخ اطفال او كبار 3 D + 4 D', 'b4') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1008', 'حنان', 'جميع الفحوص ما عدا الاتى : 1 -دوبلر على الكلى المزروعه والغير مزروعه 2 - الوصله الوريديه 3- دوبلر على القضيب 4- سونار عضلات ومفاصل 4- 3D - 4 D 5- دوبلر على المخ كبار 6- دوبلر الوصلة الوريدية', 'b4') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1009', 'اسماء احمد', 'جميع الفحوص ما عدا الاتى : 1 - الوصله الوريديه 3- دوبلر على الخصيه 4 - دوبلر على القضيب 5- سونار عضلات ومفاصل 6- دوبلر على المخ اطفال او كبار 4 D - 3 D', 'b4') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1010', 'د/ لمياء الشرقاوى', 'تعمل الاتى : 1 - سونار بطن وحوض + الغده + دوبلر على الاورده والشرايين+ الانسجه الرخاويه فقط+سونار مهبلى', 'b4') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1011', 'د/ جورج', 'جميع الفحوص ما عدا الاتى : 1 - الوصله الوريديه 2- دوبلر على الكلى المزروعه دوبلر على القضيب دوبلر على الشرايين للاطراف سونار عضلات ومفاصل سونار على البروستاتا من خلال الشرج سحب العينات دوبلر على المخ اطفال او كبار 3 D + 4 D', 'b3') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1012', 'وليد امام', 'جميع الفحوصات ماعدا ( دوبلر الطرفين العلويين – سونار القضيب و المفاصل و العضلات – دوبلر الكلى )', 'b3') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1013', 'مراد', 'جميع الفحوصات ماعدا ( الثدى – المهبلى – القضيب ) متاح حجز ( thyroid elestography us ) + Trans Cranial', 'b3') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1014', 'ساره نجم', 'جميع الفحوصات ماعدا ( دوبلر الطرفين العلويين – سونار القضيب و المفاصل و العضلات – دوبلر الكلى )', 'b3') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1015', 'محمد الجباس', 'فحوصات عاديه فقط غده و بطن و حوض لا يوجد اى دوبلر او اى فحص معقد', 'b3') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1016', 'الشناوى', 'جميع الفحوصات ماعدا ( دوبلر القضيب – سونار البروستاتا من خلال الشرج – سونار الثدى – سونار مهبلى – سونار المفاصل و العضلات - دوبلر الكلى )', 'b3') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1017', 'اسماء احمد', 'جميع الفحوصات ماعدا (دوبلر الكلى – دوبلر الطرفين العلويين - سونار عضلات ومفاصل)', 'b3') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1018', 'ايمان', 'فحوصات عاديه سونار و متاح انسجه رخويه', 'b3') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1019', 'انس', 'جميع الفحوصات ماعدا ( دوبلر الكلى المزروعه – دوبلر الوصله الوريديه- المفاصل و العضلات )', 'b3') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1020', 'محمد شوقى', 'جميع الفحوصات ماعدا ( سونار المفاصل و العضلات – دوبلر القضيب -', 'b3') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1021', 'د / عبد القادر', 'ملحوظه : سونار البروستاتا من خلال الشرج متوفر بفرع السيده زينب مع د / عبد القادر فقط .وكذلك فحص ال thyroid elestography us', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1023', 'أمتياز', 'فحوصات عاديه فقط غده و بطن و حوض لا يوجد اى دوبلر او اى فحص معقد سونار على المخ كبار - دوبلر الكلى )', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1024', 'خالد السيد', 'كل الفحوصات ماعدا ( الفتق الاربى للأناث – القضيب – المفاصل – العضلات – الحمل – الكيس الدهنى – بروستاتا عن طريق الشرج -- دوبلر غسيل الكلى )', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1025', 'محمد عبد القادر', 'كل الفحوصات ماعدا ( القضيب – المفاصل – العضلات – دوبلر غسيل الكلى )', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1026', 'احمد محمود', 'كل الفحوصات ماعدا ( القضيب – المفاصل – العضلات – بروستاتا عن طريق الشرج - دوبلر غسيل الكلى )', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1027', 'امنية', 'فحوصات عاديه فقط غده و بطن و حوض ومتاح دوبلر اوردة وشرايين ساقين و شرايين رقبة', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1028', 'ايات', 'فحوصات عاديه فقط غده و بطن و حوض ومتاح دوبلر اوردة وشرايين ساقين و شرايين رقبة', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1029', 'نهى', 'فحوصات عاديه فقط غده و بطن و حوض لا يوجد اى دوبلر او اى فحص معقد', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1030', 'اسلام', 'كل الفحوصات ماعدا ( القضيب – المفاصل – العضلات – بروستاتا عن طريق الشرج - دوبلر غسيل الكلى )', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1031', 'اسامه', 'كل الفحوصات ماعدا ( الفتق الاربى – القضيب – المفاصل - بروستاتا عن طريق الشرج – العضلات – دوبلر الكلى – الوريد البابى الكبدى – الكيس الدهنى – بروستاتا عن طريق الشرج – اورده الحوض – دوبلر غسيل الكلى )', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1032', 'ايناس', 'شغاله فحوصات الحمل فقط + سونار مهبلى', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1033', 'مصطفى', 'كل الفحوصات ماعدا ( القضيب – المفاصل – بروستاتا عن طريق الشرج – العضلات – دوبلر غسيل الكلى )', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1034', 'احمد هشام', 'كل الفحوصات ماعدا ( القضيب – المفاصل – بروستاتا عن طريق الشرج – العضلات – دوبلر غسيل الكلى )', 'b6') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1035', 'د / اسلام هاني', 'ملحوظه : سونار البروستاتا من خلال الشرج متوفر بفرع المقطم مع د / اسلام هاني فقط .', 'b2') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1036', ' د. ريم البرنس', 'فحص ال thyroid elestography us متاح مع د. ريم البرنس', 'b2') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1037', 'عمر معاويه', 'سونار المفاصل و العضلات و القضيب و بالحجز من الفرع و يحدد موعد', 'b2') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1038', 'ريهام', 'شغاله فحوصات عاديه و شغاله سونار مفاصل و كيس دهنى و عضلات لكن مش متاح معاها اى دوبلر', 'b2') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1039', 'اسامه', 'كل الفحوصات ماعدا ( الفتق الاربى – القضيب – المفاصل – العضلات – دوبلر الكلى و سونار البروستاتا – الوريد البابى الكبدى – الكيس الدهنى – اورده الحوض – دوبلر غسيل الكلى )', 'b2') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1040', 'علاء امين', 'شغال كل الفحوص + اغذ عينات', 'b2') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1041', 'اسلام سامى', 'كل الفحوصات ماعدا ( القضيب – المفاصل – العضلات – دوبلر غسيل الكلى )', 'b2') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1042', 'عمرو سمير', 'شغال كله ماعدا ( الوصله الوريديه و الوريد البابى الكبدى و سونار البروستاتا و دوبلرالقضيب - دوبلر الذراع – ودوبلر أوردة الرقبة – سونار مهبلى – فحوصات الحمل – سونار المفاصل )', 'b2') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1043', 'خالد سليم', 'شغال كله ماعدا ( الوصله الوريديه و الوريد البابى الكبدى و سونار البروستاتا و دوبلرالقضيب - دوبلر الذراع – ودوبلر أوردة الرقبة – سونار مهبلى – فحوصات الحمل – سونار المفاصل )', 'b1') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1044', 'احمد حجاج', 'متاح معه فحوصات عاديه سونار و دوبلر ماعدا الاتى ( سونار العضلات و المفاصل –دوبلرالاطراف العلويه كله- رباعي الابعاد - T.V –thyroid elestography - سونار البروستاتا من خلال الشرج )', 'b1') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1045', 'محمود زايد', 'شغال كل الفحوصات متاح حجز ال AVF الخاص بغسيل الكلى + متاح عمل سونار جمجمه للاطفال اقل من سنة + thyroid elestography us', 'b1') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1046', 'محمد مختار', 'متاح معه فحوصات عاديه و سونار و مامو ماعدا الاتى ( سونار العضلات و المفاصل – دوبلر شرايين الاطراف السفليه و العلويه كلها – سونار البروستاتا من خلال الشرج )', 'b1') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1047', 'خالد مهدى', 'متاح معه فحوصات عاديه و سونار و مامو ماعدا الاتى ( سونار العضلات و المفاصل – دوبلرالاطراف العلويه كلها – سونار البروستاتا من خلال الشرج ) متاح thyroid elestography us )', 'b1') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1048', 'مروه نصر', 'جميع الفحوصات عدا Doppler scrotal- -Hepatic - Doppler Penile - 3D . 4D - M.S.K غير متاح thyroid elestography us', 'b1') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1049', 'ايمان', 'جميع الفحوصات عدا Doppler scrotal- -Hepatic - Doppler Penile - 3D . 4D - M.S.K غير متاح thyroid elestography us', 'b1') ON CONFLICT (id) DO NOTHING;
INSERT INTO doctors (id, name, specialty, branch_id) VALUES ('doc_us_1050', 'ريم البرنس', 'متاح حجز ال 4 D و ال U.S thyroid elestography -- متاح عينات الثدي والغده الدرقيه و المامو', 'b1') ON CONFLICT (id) DO NOTHING;

-- 3. Devices
INSERT INTO devices (id, name, type, branch_id, status) VALUES ('dev_1774007581385', 'Ct', 'CT Scan', 'b1', 'Maintenance') ON CONFLICT (id) DO NOTHING;
INSERT INTO devices (id, name, type, branch_id, status) VALUES ('dev_1774431088999', 'Mri colas', 'MRI', 'b6', 'Available') ON CONFLICT (id) DO NOTHING;
INSERT INTO devices (id, name, type, branch_id, status) VALUES ('dev_1775495162234', 'MRI-close', 'MRI', 'b3', 'Maintenance') ON CONFLICT (id) DO NOTHING;
INSERT INTO devices (id, name, type, branch_id, status) VALUES ('dev_1779209057569', 'قق', 'X-Ray', 'b1', 'Available') ON CONFLICT (id) DO NOTHING;

-- 4. Users
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_admin', 'مدير النظام', 'admin', 'admina', NULL, 'Administrator', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_mgr_b1', 'مدير فرع روكسي', 'admin.roxy', 123.0, 'b1', 'Branch Manager', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_mgr_b2', 'مدير فرع المقطم', 'admin.mokattam', 123.0, 'b2', 'Branch Manager', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_mgr_b3', 'مدير فرع فيصل', 'admin.faisal', 123.0, 'b3', 'Branch Manager', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_mgr_b4', 'مدير فرع حدائق الأهرام', 'admin.hadaek', 123.0, 'b4', 'Branch Manager', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_mgr_b5', 'مدير فرع المنيا', 'admin.minya', 123.0, 'b5', 'Branch Manager', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_mgr_b6', 'مدير فرع السيدة زينب', 'admin.sayeda', 123.0, 'b6', 'Branch Manager', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_mgr_b7', 'مدير فرع ميت غمر', 'admin.mitghamr', 123.0, 'b7', 'Branch Manager', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_1', 'Adel Ahmed', 'Adel.ahmed', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_2', 'Aya Abdelmohsen', 'aya.mohsen', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_3', 'Eman Elfeky', 'Eman.Elfeky', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_4', 'Eman Khaled', 'Eman.Khaled', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_5', 'Hamed Elbadry Saied', 'hamed.elbadry', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_6', 'Hend Yassen', 'hend.yassen', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_7', 'Mai Mohamed', 'Mai.Mohamed', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_8', 'Marwa Ahmed', 'Marwa.Ahmed', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_9', 'Mohamed Adel', 'Mohamed.adel', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_10', 'Mohamed Shehata', 'Mohamed.Shehata', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_11', 'mostafa shehata', 'mostafa.shehata', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_12', 'Nada Sayed', 'Nada.Sayed', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_13', 'saad mohamed', 'saad.mohamed', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_14', 'sayed shaaban', 'sayed.shaaban', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_15', 'Yasmin Hassan Ibrahim', 'yasmin.ibrahim', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_16', 'Ziad Ehab', 'ziad.ehab', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_17', 'عبدالرحمن عمرو', 'abdelrahman.amr', 123.0, NULL, 'Administrator', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_18', 'عبدالعزيز خالد', 'abdelraziez.khaled', 123.0, NULL, 'Administrator', 'Active') ON CONFLICT (id) DO NOTHING;
INSERT INTO users (id, name, email, password, branch_id, role, status) VALUES ('u_cc_19', 'head of callcenter', 'eslam.elzorkany', 123.0, NULL, 'Call Center', 'Active') ON CONFLICT (id) DO NOTHING;

-- 5. Schedules
INSERT INTO schedules (id, doctor_id, branch_id, day_of_week, start_time, end_time, status) VALUES ('sch_1782254581524', 'doc_us_1014', 'b3', 'السبت', '01:42:00', '07:43:00', 'Available') ON CONFLICT (id) DO NOTHING;
INSERT INTO schedules (id, doctor_id, branch_id, day_of_week, start_time, end_time, status) VALUES ('sch_1782254742926', 'doc_us_1011', 'b3', 'السبت', '15:45:00', '07:45:00', 'Available') ON CONFLICT (id) DO NOTHING;
INSERT INTO schedules (id, doctor_id, branch_id, day_of_week, start_time, end_time, status) VALUES ('sch_1782303956990', 'doc_us_1001', 'b4', 'الإثنين', '15:25:00', '19:25:00', 'Available') ON CONFLICT (id) DO NOTHING;

-- 6. Tests
INSERT INTO tests (id, name_ar, name_en, category, price, instructions, device_id, specific_days, all_week) VALUES ('test_1773888652196', 'اشعة مقطعيه على المخ', 'ct brain', 'Radiology', 200.0, 'متاح 24 ساعه', NULL, NULL, TRUE) ON CONFLICT (id) DO NOTHING;

-- 7. DeviceLogs
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773878652448', NULL, 'dexa', 'روكسي', 'المقطم', 'صيانة', 'صيانة', 'Test reason for moving the device', '2026-03-19T00:04:12.448Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773878888283', NULL, 'dexa', 'المقطم', 'المقطم', 'صيانة', 'متاح العمل', 'تجربه نقل', '2026-03-19T00:08:08.283Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773879752589', NULL, 'dexa', 'المقطم', 'المقطم', 'متاح العمل', 'صيانة', 'تجربه', '2026-03-19T00:22:32.589Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773887422377', NULL, 'dexa', 'المقطم', 'المقطم', 'متاح العمل', 'صيانة', 'صص', '2026-03-19T02:30:22.377Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773888125269', NULL, 'dexa', 'المقطم', 'المقطم', 'صيانة', 'متاح العمل', 'aa', '2026-03-19T02:42:05.269Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773888533024', NULL, 'dexa', 'المقطم', 'المقطم', 'متاح العمل', 'صيانة', 'ر', '2026-03-19T02:48:53.024Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773888556333', NULL, 'dexa', 'المقطم', 'المقطم', 'صيانة', 'متاح العمل', 'ييي', '2026-03-19T02:49:16.333Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773889032248', NULL, 'dexa', 'المقطم', 'المقطم', 'متاح العمل', 'صيانة', 2.0, '2026-03-19T02:57:12.248Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773889051372', NULL, 'dexa', 'المقطم', 'المقطم', 'صيانة', 'متاح العمل', 2.0, '2026-03-19T02:57:31.372Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773889367158', NULL, 'dexa', 'المقطم', 'حدائق الأهرام', 'متاح العمل', 'صيانة', 'ssss', '2026-03-19T03:02:47.158Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773889788578', NULL, 'dexa', 'حدائق الأهرام', 'المقطم', 'صيانة', 'صيانة', 'يلا', '2026-03-19T03:09:48.578Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773890085414', NULL, 'dexa', 'المقطم', 'المقطم', 'صيانة', 'متاح العمل', 'شش', '2026-03-19T03:14:45.414Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773896547466', NULL, 'dexa', 'المقطم', 'حدائق الأهرام', 'متاح العمل', 'صيانة', 'test', '2026-03-19T05:02:27.466Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773896573082', NULL, 'dexa', 'حدائق الأهرام', 'روكسي', 'صيانة', 'متاح العمل', 'test', '2026-03-19T05:02:53.082Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773933168430', NULL, 'dexa', 'روكسي', 'روكسي', 'متاح العمل', 'صيانة', 110011.0, '2026-03-19T15:12:48.430Z', 'مدير النظام الأساسي') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1773934427172', NULL, 'dexa', 'روكسي', 'روكسي', 'صيانة', 'متاح العمل', 'تجربه', '2026-03-19T15:33:47.172Z', 'عبدالعزيز خالد') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1774266226938', 'dev_1774007581385', 'Ct', 'روكسي', 'روكسي', 'متاح العمل', 'صيانة', '["View Tests","View Devices","View Doctors","View Schedules"]', '2026-03-23T11:43:46.938Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1774267206165', 'dev_1774007581385', 'Ct', 'روكسي', 'روكسي', 'متاح العمل', 'صيانة', 33.0, '2026-03-23T12:00:06.165Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1774267218226', 'dev_1774007581385', 'Ct', 'روكسي', 'روكسي', 'صيانة', 'متاح العمل', 333.0, '2026-03-23T12:00:18.226Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1774267225843', 'dev_1774007581385', 'Ct', 'روكسي', 'روكسي', 'متاح العمل', 'صيانة', 333.0, '2026-03-23T12:00:25.843Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1774346434932', 'dev_1774007581385', 'Ct', 'روكسي', 'روكسي', 'صيانة', 'متاح العمل', 'fvdfd', '2026-03-24T10:00:34.932Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1774346803297', 'dev_1774007581385', 'Ct', 'روكسي', 'روكسي', 'متاح العمل', 'صيانة', 'k', '2026-03-24T10:06:43.297Z', 'مدير النظام') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1774431269962', 'dev_1774431088999', 'Mri colas', 'السيده زينب', 'السيده زينب', 'متاح العمل', 'متاح العمل', NULL, '2026-03-25T09:34:29.962Z', 'مدير فرع السيدة زينب') ON CONFLICT (id) DO NOTHING;
INSERT INTO device_logs (id, device_id, device_name, old_branch, new_branch, old_status_str, new_status_str, reason, date, user_name) VALUES ('log_1775495293547', 'dev_1775495162234', 'MRI-close', 'فيصل', 'فيصل', 'متاح العمل', 'صيانة', 'الجهاز به عطل', '2026-04-06T17:08:13.547Z', 'مدير فرع فيصل') ON CONFLICT (id) DO NOTHING;

-- 8. Notifications
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773878656084', 'تم نقل الجهاز (dexa) من (روكسي) إلى (المقطم) - السبب: Test reason for moving the device', 'warning', '2026-03-19T00:04:16.084Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773878890944', 'تم تحديث جاهزية (dexa) بفرع (المقطم) إلى (متاح العمل) - السبب: تجربه نقل', 'success', '2026-03-19T00:08:10.944Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773879755466', 'تم تحديث جاهزية (dexa) بفرع (المقطم) إلى (صيانة) - السبب: تجربه', 'warning', '2026-03-19T00:22:35.466Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773887427388', 'تم تحديث جاهزية (dexa) بفرع (المقطم) إلى (صيانة) - السبب: صص', 'warning', '2026-03-19T02:30:27.388Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773888127932', 'تم تحديث جاهزية (dexa) بفرع (المقطم) إلى (متاح العمل) - السبب: aa', 'success', '2026-03-19T02:42:07.932Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773888533025', 'تم تحديث جاهزية (dexa) بفرع (المقطم) إلى (صيانة) - السبب: ر', 'warning', '2026-03-19T02:48:53.025Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773888556335', 'تم تحديث جاهزية (dexa) بفرع (المقطم) إلى (متاح العمل) - السبب: ييي', 'success', '2026-03-19T02:49:16.335Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773889032249', 'تم تحديث جاهزية (dexa) بفرع (المقطم) إلى (صيانة) - السبب: 2', 'warning', '2026-03-19T02:57:12.249Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773889051373', 'تم تحديث جاهزية (dexa) بفرع (المقطم) إلى (متاح العمل) - السبب: 2', 'success', '2026-03-19T02:57:31.373Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773889367159', 'تم نقل الجهاز (dexa) من (المقطم) إلى (حدائق الأهرام) - السبب: ssss', 'warning', '2026-03-19T03:02:47.159Z', '["u_admin","u_cc_19"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773889788579', 'تم نقل الجهاز (dexa) من (حدائق الأهرام) إلى (المقطم) - السبب: يلا', 'warning', '2026-03-19T03:09:48.579Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773890085416', 'قام [مدير النظام] بتحديث جاهزية (dexa) بفرع (المقطم) إلى (متاح العمل) - السبب: شش', 'success', '2026-03-19T03:14:45.416Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773896547467', 'قام [مدير النظام] بنقل الجهاز (dexa) من (المقطم) إلى (حدائق الأهرام) - السبب: test', 'warning', '2026-03-19T05:02:27.467Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773896573083', 'قام [مدير النظام] بنقل الجهاز (dexa) من (حدائق الأهرام) إلى (روكسي) - السبب: test', 'success', '2026-03-19T05:02:53.083Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773933168431', 'قام [مدير النظام الأساسي] بتحديث جاهزية (dexa) بفرع (روكسي) إلى (صيانة) - السبب: 00110011', 'warning', '2026-03-19T15:12:48.431Z', '["u_admin","u_cc_19"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1773934427173', 'قام [عبدالعزيز خالد] بتحديث جاهزية (dexa) بفرع (روكسي) إلى (متاح العمل) - السبب: تجربه', 'success', '2026-03-19T15:33:47.173Z', '["","u_cc_19","u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1774266226938', 'قام [مدير النظام] بتحديث جاهزية (Ct) بفرع (روكسي) إلى (صيانة) - السبب: ["View Tests","View Devices","View Doctors","View Schedules"]', 'warning', '2026-03-23T11:43:46.938Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1774267206165', 'قام [مدير النظام] بتحديث جاهزية (Ct) بفرع (روكسي) إلى (صيانة) - السبب: 33', 'warning', '2026-03-23T12:00:06.165Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1774267218227', 'قام [مدير النظام] بتحديث جاهزية (Ct) بفرع (روكسي) إلى (متاح العمل) - السبب: 333', 'success', '2026-03-23T12:00:18.227Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1774267225843', 'قام [مدير النظام] بتحديث جاهزية (Ct) بفرع (روكسي) إلى (صيانة) - السبب: 333', 'warning', '2026-03-23T12:00:25.843Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1774346434933', 'قام [مدير النظام] بتحديث جاهزية (Ct) بفرع (روكسي) إلى (متاح العمل) - السبب: fvdfd', 'success', '2026-03-24T10:00:34.933Z', '["u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1774346803298', 'قام [مدير النظام] بتحديث جاهزية (Ct) بفرع (روكسي) إلى (صيانة) - السبب: k', 'warning', '2026-03-24T10:06:43.298Z', '["u_admin","u_cc_3"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1774431269963', 'قام [مدير فرع السيدة زينب] بتحديث جاهزية (Mri colas) بفرع (السيده زينب) إلى (متاح العمل) - السبب: ', 'success', '2026-03-25T09:34:29.963Z', '["u_mgr_b6","u_cc_3","u_admin"]') ON CONFLICT (id) DO NOTHING;
INSERT INTO notifications (id, message, type, timestamp, read_by) VALUES ('notif_1775495293548', 'قام [مدير فرع فيصل] بتحديث جاهزية (MRI-close) بفرع (فيصل) إلى (صيانة) - السبب: الجهاز به عطل', 'warning', '2026-04-06T17:08:13.548Z', '["u_mgr_b3","u_cc_3","u_admin"]') ON CONFLICT (id) DO NOTHING;

SET session_replication_role = 'origin';